"""Inspect the WISE architecture with ``python -m wise --describe``."""

import argparse
import json
from pathlib import Path
import sys
import tomllib

from . import __version__
from .config import load_config
from .errors import RuntimeNotAvailableError

DESCRIPTION = """WISE — Which-Why Informed Semantic Explorer
Release: {version} | framework and interfaces
Runtime implementation and experiment assets: awaiting migration

wise/
  agent.py        Algorithm 1: memory → reasoning → explore / execute
  types.py        RGB observations, poses, memory cues, task-order contracts
  memory.py       §3.1.1: short-term geometric memory
  keyframes.py    §3.1.2: cluster/entropy keyframe selection
  vlm.py          §3.1.2, A.2: non-blocking submit / drain-ready boundary
  grounding.py    A.8–A.9: vocabulary and mechanics validation
  saeg.py         §3.1.2: entities, spatial instances, affordance relations
  retrieval.py    §3.1.3: two-level visual/affordance retrieval
  scheduler.py    §3.2: opportunistic task selection
  exploration.py §3.3: global quadtree → regional frontier → local Voronoi
  controllers.py Fig. 2: VPT-Nav navigation and Steve-1 instruction adapters
  config.py       TOML manifest inspection; independent of baseline Hydra

Task policies: ABA-Sparse = fixed_order; ABC-Sparse = reorderable.
VLM inference must remain outside the blocking online action path.
Runtime methods raise RuntimeNotAvailableError until their implementations migrate.
Paper results are reported experiments, not outputs generated by this release.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Inspect the WISE paper framework.")
    parser.add_argument("--version", action="version", version=f"WISE {__version__}")
    parser.add_argument("--describe", action="store_true", help="show architecture (default)")
    parser.add_argument("--config", type=Path, help="also inspect a TOML configuration manifest")
    parser.add_argument(
        "--evaluate", action="store_true",
        help="check evaluation availability (runtime is awaiting migration)",
    )
    args = parser.parse_args(argv)
    if args.evaluate:
        print(f"error: {RuntimeNotAvailableError('WISE evaluation')}", file=sys.stderr)
        return 2

    print(DESCRIPTION.format(version=__version__))
    if args.config is not None:
        try:
            config = load_config(args.config)
        except (OSError, tomllib.TOMLDecodeError) as error:
            print(f"error: cannot inspect {args.config}: {error}", file=sys.stderr)
            return 2
        print(f"Manifest: {args.config}\n")
        print(json.dumps(config, indent=2, ensure_ascii=False, default=str))
        print("\nManifest parsed for inspection; no runtime components were initialized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
